#!/bin/bash

# Copyright 2015 Davide Giannella
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ----------------------------------------------------------------------
# 
# A very simple shell script for OSX that will find your process for
# the gdrive app, kill it and restart it.
#
# Often when switching through networks: travelling, VPNs, etc, the
# app won't connect to GDrive unless you simply restart it.
#
# Usage: simply execute the script.

set -e

APP="/Applications/Google Drive.app"

pid=`ps -ef | grep "$APP" | grep -v 'grep' | awk '{print $2}'`
if [ ! -z "$pid" ]
then
    echo "Killing ${pid}"
    kill $pid
    while ps -ef | grep "$pid" | grep -v 'grep' > /dev/null ; do
        echo -n .
        sleep 5
    done
    echo "Process ${pid} killed."
fi

echo "Starting $APP"
open -a "$APP"
